<a href="https://colab.research.google.com/github/Izumiiiii17/AI-ML/blob/main/AIML_LAB_SHEET2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
A1=np.array([1,2,3])
print(A1)

[1 2 3]


In [ ]:
type(A1)

numpy.ndarray

In [ ]:
A1.shape

(3,)

In [ ]:
A1.size

3

In [ ]:
#2D ARRAY
A2=np.array([[1,2,3],[4,5,6]])
print(A2)

[[1 2 3]
 [4 5 6]]


In [ ]:
type(A2)

numpy.ndarray

In [ ]:
A2.size

6

In [ ]:
A2.shape

(2, 3)

In [ ]:
A2.ndim

2

In [ ]:
#3D ARRAY
A3=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(A3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
type(A3)

numpy.ndarray

In [ ]:
A3.size

9

In [ ]:
A3.shape

(1, 3, 3)

In [ ]:
A3.ndim

3

In [ ]:
z1=np.zeros(3)
z1

array([0., 0., 0.])

In [ ]:
#CHANGING DATA TYPE

z1=np.zeros(3,dtype=int)
z1

array([0, 0, 0])

In [ ]:
z1.shape

(3,)

In [ ]:
z1.size

3

In [ ]:
z1.ndim

1

In [ ]:
type(z1)

numpy.ndarray

In [ ]:
z2=np.zeros((3,4))
z2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
z2=np.zeros((3,4),dtype=int)
z2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
type(z2)

numpy.ndarray

In [ ]:
z2.shape

(3, 4)

In [ ]:
z2.size

12

In [ ]:
z2.ndim

2

In [ ]:
z3=np.zeros((2,3,4))
z3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
z3=np.zeros((2,3,4),dtype=int)
z3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [ ]:
z3.shape

(2, 3, 4)

In [ ]:
z3.size

24

In [ ]:
z3.ndim

3

In [ ]:
type(z3)

numpy.ndarray

In [ ]:
#1D 0NES ARRAY
a1=np.ones(3)
a1

array([1., 1., 1.])

In [ ]:
a1=np.ones(3,dtype=int)
a1
print(type(a1))
print(a1.shape)
print(a1.size)
print(a1.ndim)

<class 'numpy.ndarray'>
(3,)
3
1


In [ ]:
#2D ONES ARRAY

a2=np.ones([3,4])
a2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
a2=np.ones([3,4],dtype=int)
a2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
print(type(a2))
print(a2.shape)
print(a2.size)
print(a2.ndim)

<class 'numpy.ndarray'>
(3, 4)
12
2


In [ ]:
#3D ONES ARRAY

a3=np.ones([4,2,3])
a3

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
a3=np.ones([4,2,3],dtype=int)
a3

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [ ]:
print(type(a3))
print(a3.shape)
print(a3.size)
print(a3.ndim)

<class 'numpy.ndarray'>
(4, 2, 3)
24
3


In [ ]:
#1D FULL ARRAY
#EASY TO NAVIGATE

f1=np.full(3,9)
print(f1)

[9 9 9]


In [ ]:
f1=np.full(3,9,dtype=int)
print(f1)
print(type(f1))
print(f1.shape)
print(f1.size)
print(f1.ndim)

[9 9 9]
<class 'numpy.ndarray'>
(3,)
3
1


In [ ]:
#2D FULL ARRAY

f2=np.full([2,3],9)
print(f2)

[[9 9 9]
 [9 9 9]]


In [ ]:
f2=np.full([2,3],9,dtype=int)
print(f2)
print(type(f2))
print(f2.shape)
print(f2.size)
print(f2.ndim)

[[9 9 9]
 [9 9 9]]
<class 'numpy.ndarray'>
(2, 3)
6
2


In [ ]:
#3D FULL ARRAY

f3=np.full([4,2,3],9)
print(f3)

[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]


In [ ]:
f3=np.full([4,2,3],9,dtype=int)
print(f3)
print(type(f3))
print(f3.shape)
print(f3.size)
print(f3.ndim)

[[[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]

 [[9 9 9]
  [9 9 9]]]
<class 'numpy.ndarray'>
(4, 2, 3)
24
3


In [ ]:
#ADD

a=np.array([1,2,3])
b=np.array([1,2,3])

add=np.add(a,b)
add

array([2, 4, 6])

In [ ]:
#SUBTRACT

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.subtract(a,b)
sub

array([ 1,  2, 10])

In [ ]:
#MULTIPLY

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.multiply(a,b)
sub

array([ 20,  80, 200])

In [ ]:
#DIVIDE

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.divide(a,b)
sub

array([1.25, 1.25, 2.  ])

In [ ]:
#MOD

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.mod(a,b)
sub

array([1, 2, 0])

In [ ]:
#POWER

a=np.array([5,10,20])
b=np.array([4,8,10])

sub=np.power(a,b)
sub

array([           625,      100000000, 10240000000000])